In [1]:
import pandas as pd
import numpy as np

In [2]:
import cv2
image = cv2.imread("/Users/hyojin/DigitalImageProcessing/HE test/Fig0316(1)(top_left).jpg", cv2.IMREAD_COLOR)
image2 = cv2.imread("/Users/hyojin/DigitalImageProcessing/HE test/Fig0316(1)(top_left).jpg", cv2.IMREAD_GRAYSCALE)
image2.shape

(500, 500)

In [3]:
kernel = -np.ones((3,3))
kernel[1,1] = 8 + 1.2
kernel

array([[-1. , -1. , -1. ],
       [-1. ,  9.2, -1. ],
       [-1. , -1. , -1. ]])

In [4]:
image2[110:113,450:453]

array([[196, 196, 198],
       [196, 198, 202],
       [190, 194, 196]], dtype=uint8)

In [6]:
np.around(np.sum(np.multiply(image2[110:113,450:453], kernel)))

254.0

In [8]:
size = 3
radius = int((size-1)/2)
radius


1

In [9]:
width, height = image.shape[0], image.shape[1]
result = np.zeros((width-2*radius, height-2*radius))
for i in range(width-2*radius):
    for j in range(height-2*radius):
        result[i,j] = np.around(np.sum(np.multiply(image[i:i+size,j:j+size], kernel)))

In [11]:
np.array(result, dtype='uint8')

array([[219, 219, 219, ...,  45, 242, 236],
       [219, 219, 219, ..., 249, 231, 228],
       [219, 219, 219, ...,  24, 139, 164],
       ...,
       [105, 219, 219, ..., 158, 119, 118],
       [124, 201, 219, ..., 250,  82, 113],
       [176, 162, 219, ..., 196,  87, 152]], dtype=uint8)

In [13]:
cv2.imshow("airplane", np.array(result, dtype='uint8'))
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [16]:
kernel2 = np.zeros((size, size))
kernel2[radius-1, radius] = kernel2[radius+1, radius] = -1
kernel2[radius, radius-1] = kernel2[radius, radius+1] = -1
kernel2[radius, radius] = 4 + 1.2
kernel2

array([[ 0. , -1. ,  0. ],
       [-1. ,  5.2, -1. ],
       [ 0. , -1. ,  0. ]])

In [17]:
hsi = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
hsi

array([[[  0,   0, 132],
        [  0,   0, 132],
        [  0,   0, 132],
        ...,
        [  0,   0, 191],
        [  0,   0, 191],
        [  0,   0, 184]],

       [[  0,   0, 132],
        [  0,   0, 132],
        [  0,   0, 132],
        ...,
        [  0,   0, 190],
        [  0,   0, 190],
        [  0,   0, 179]],

       [[  0,   0, 132],
        [  0,   0, 132],
        [  0,   0, 132],
        ...,
        [  0,   0, 175],
        [  0,   0, 175],
        [  0,   0, 166]],

       ...,

       [[  0,   0, 149],
        [  0,   0, 132],
        [  0,   0, 132],
        ...,
        [  0,   0, 248],
        [  0,   0, 242],
        [  0,   0, 242]],

       [[  0,   0, 151],
        [  0,   0, 138],
        [  0,   0, 132],
        ...,
        [  0,   0, 242],
        [  0,   0, 242],
        [  0,   0, 235]],

       [[  0,   0, 156],
        [  0,   0, 145],
        [  0,   0, 132],
        ...,
        [  0,   0, 240],
        [  0,   0, 240],
        [  0,   0, 224]]

In [22]:
rgb = cv2.cvtColor(hsi, cv2.COLOR_HSV2RGB)

In [26]:
hsi2 = hsi
hsi2[:,:,2] = 0.5*hsi[:,:,2]
rgb2 = cv2.cvtColor(hsi2, cv2.COLOR_HSV2RGB)

In [44]:
result = image
result[:,:,2] = np.array(255*(image[:,:,2]/255)**0.67)
result = np.array(result, dtype='uint8')
# result = cv2.cvtColor(result, cv2.COLOR_HSV2BGR)

In [36]:
import colorsys

In [40]:
colorsys.hsv_to_rgb(50, 50, 100)[0]

100

In [45]:
width, height, channel = image.shape[0], image.shape[1], image.shape[2]
for i in range(width):
    for j in range(height):
        result[i,j,0],result[i,j,1],result[i,j,2] = colorsys.hsv_to_rgb(result[i,j,0], result[i,j,1], result[i,j,2])

In [46]:

cv2.imshow("airplane", result)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [10]:
result

array([[ 475.,  475.,  475., ...,  557.,  754.,  748.],
       [ 475.,  475.,  475., ...,  505.,  743.,  740.],
       [ 475.,  475.,  475., ...,  536.,  651.,  676.],
       ...,
       [ 361.,  475.,  475., ...,  926.,  887.,  886.],
       [ 380.,  457.,  475., ..., 1018.,  850.,  881.],
       [ 432.,  418.,  475., ...,  964.,  855.,  920.]])

In [22]:
image2[111,451]

198

In [26]:
image2[110:111,451]

array([196], dtype=uint8)

In [19]:
np.sum(np.multiply(image2[110:113,450:453], kernel2d))

196.6032710919388

In [4]:
image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

In [5]:
image.shape

(500, 500, 3)

In [6]:
image

array([[[  0,   0, 132],
        [  0,   0, 132],
        [  0,   0, 132],
        ...,
        [  0,   0, 191],
        [  0,   0, 191],
        [  0,   0, 184]],

       [[  0,   0, 132],
        [  0,   0, 132],
        [  0,   0, 132],
        ...,
        [  0,   0, 190],
        [  0,   0, 190],
        [  0,   0, 179]],

       [[  0,   0, 132],
        [  0,   0, 132],
        [  0,   0, 132],
        ...,
        [  0,   0, 175],
        [  0,   0, 175],
        [  0,   0, 166]],

       ...,

       [[  0,   0, 149],
        [  0,   0, 132],
        [  0,   0, 132],
        ...,
        [  0,   0, 248],
        [  0,   0, 242],
        [  0,   0, 242]],

       [[  0,   0, 151],
        [  0,   0, 138],
        [  0,   0, 132],
        ...,
        [  0,   0, 242],
        [  0,   0, 242],
        [  0,   0, 235]],

       [[  0,   0, 156],
        [  0,   0, 145],
        [  0,   0, 132],
        ...,
        [  0,   0, 240],
        [  0,   0, 240],
        [  0,   0, 224]]

In [8]:
image[:,:,2] = np.zeros((500,500))

In [9]:
image

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [29]:
img = image[:,:,2]

In [32]:
width, height = img.shape[0], img.shape[1]
max = np.max(img) + 1
min = np.min(img)
num_pixel = width*height

#scale histogram
hist = np.zeros(max)
#cdf of scale histogram
sum_hist = np.zeros(max)
#normalized sum
norm_hist = np.zeros(max)

result = np.zeros((width, height))
sum = 0
for i in range(width):
    for j in range(height):
        hist[img[i][j]] += 1
min = sum_hist[min]
for i in range(max):
    sum+=hist[i]
    sum_hist[i] = sum
    norm_hist[i] = np.around((max-1)*(sum_hist[i]-min)/(num_pixel-min))
for i in range(width):
    for j in range(height):
        result[i][j] = norm_hist[img[i][j]]

In [33]:
result.shape

(500, 500)

In [34]:
rs = image
rs.shape

(500, 500, 3)

In [36]:
rs[:,:,2] = result

In [39]:
result

array([[ 18.,  18.,  18., ..., 115., 115., 103.],
       [ 18.,  18.,  18., ..., 112., 112.,  97.],
       [ 18.,  18.,  18., ...,  91.,  91.,  80.],
       ...,
       [ 49.,  18.,  18., ..., 219., 213., 213.],
       [ 59.,  19.,  18., ..., 213., 213., 198.],
       [ 68.,  32.,  18., ..., 207., 207., 182.]])

In [38]:
rs[:,:,2]

array([[ 18,  18,  18, ..., 115, 115, 103],
       [ 18,  18,  18, ..., 112, 112,  97],
       [ 18,  18,  18, ...,  91,  91,  80],
       ...,
       [ 49,  18,  18, ..., 219, 213, 213],
       [ 59,  19,  18, ..., 213, 213, 198],
       [ 68,  32,  18, ..., 207, 207, 182]], dtype=uint8)

In [12]:
cv2.imshow("airplane", result)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [20]:
np.array([image[:,:,0], image[:,:,1], image[:,:,2]], dtype='uint8')

array([[[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0]],

       [[  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        ...,
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0],
        [  0,   0,   0, ...,   0,   0,   0]],

       [[132, 132, 132, ..., 191, 191, 184],
        [132, 132, 132, ..., 190, 190, 179],
        [132, 132, 132, ..., 175, 175, 166],
        ...,
        [149, 132, 132, ..., 248, 242, 242],
        [151, 138, 132, ..., 242, 242, 235],
        [156, 145, 132, ..., 240, 240, 224]]], dtype=uint8)

In [68]:
np.median(image[3:10,1:3])

132.0

In [47]:
total_size = size**2
radius = (size-1)/2

width, height = image.shape[0], image.shape[1]


In [58]:
radius = int(radius)

In [59]:
result = np.zeros((width-2*radius, height-2*radius))


In [60]:
for i in range(width-2):
    for j in range(height-2):
        result[i,j] += np.sum(image[i:i+size,j:j+size])/total_size

In [62]:
cv2.imshow("airplane", np.array(result, dtype='uint8'))

cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1