In [7]:
import pandas as pd
import numpy as np

In [8]:
import cv2
image1 = cv2.imread("/Users/hyojin/DigitalImageProcessing/HE test/Fig0316(1)(top_left).jpg", cv2.IMREAD_COLOR)
image2 = cv2.imread("/Users/hyojin/DigitalImageProcessing/HE test/Fig0316(2)(2nd_from_top).jpg", cv2.IMREAD_COLOR)

In [3]:
kernel = np.array([[-1, 0, 1],[-1, 0, 1],[-1, 0, 1]])

In [6]:
kernel[:,2]

array([1, 1, 1])

In [ ]:
laplacian = cv2.Laplacian(img,cv2.CV_8U,ksize=5)

In [48]:
image1_hsi = cv2.cvtColor(image1, cv2.COLOR_BGR2HSV)
image2_hsi = cv2.cvtColor(image2, cv2.COLOR_BGR2HSV)

In [61]:
image1.shape[2]

3

In [4]:
image1_hsi[:,:,2]

array([[132, 132, 132, ..., 191, 191, 184],
       [132, 132, 132, ..., 190, 190, 179],
       [132, 132, 132, ..., 175, 175, 166],
       ...,
       [149, 132, 132, ..., 248, 242, 242],
       [151, 138, 132, ..., 242, 242, 235],
       [156, 145, 132, ..., 240, 240, 224]], dtype=uint8)

In [5]:
image2_hsi[:,:,2]

array([[ 91,  91,  91, ..., 107, 107, 105],
       [ 91,  91,  91, ..., 106, 106, 104],
       [ 91,  91,  91, ..., 103, 103, 101],
       ...,
       [ 96,  91,  91, ..., 122, 121, 121],
       [ 97,  94,  91, ..., 121, 120, 119],
       [ 98,  96,  91, ..., 120, 120, 117]], dtype=uint8)

In [17]:
image2_hsi_d = image2_hsi
image2_hsi_d[:,:,2] = image2_hsi_d[:,:,2] + 100
image2_rgb_d = cv2.cvtColor(image2_hsi_d, cv2.COLOR_HSV2RGB)

In [10]:
image1_rgb = cv2.cvtColor(image1_hsi, cv2.COLOR_HSV2RGB)
image2_rgb = cv2.cvtColor(image2_hsi, cv2.COLOR_HSV2RGB)

In [20]:
cv2.imshow("sample1", image2_rgb)
cv2.imshow("sample2", image2_rgb_d)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

In [51]:
image = image2_hsi.copy()

In [52]:
radius = 1
size=3
alpha = 1.2

In [53]:
kernel = np.zeros((size, size))
kernel[radius-1, radius] = kernel[radius+1, radius] = -1
kernel[radius, radius-1] = kernel[radius, radius+1] = -1
kernel[radius, radius] = 4 + alpha

In [54]:
kernel

array([[ 0. , -1. ,  0. ],
       [-1. ,  5.2, -1. ],
       [ 0. , -1. ,  0. ]])

In [55]:
image[:,:,2]

array([[ 91,  91,  91, ..., 107, 107, 105],
       [ 91,  91,  91, ..., 106, 106, 104],
       [ 91,  91,  91, ..., 103, 103, 101],
       ...,
       [ 96,  91,  91, ..., 122, 121, 121],
       [ 97,  94,  91, ..., 121, 120, 119],
       [ 98,  96,  91, ..., 120, 120, 117]], dtype=uint8)

In [57]:
width, height = image.shape[0], image.shape[1]
result = image[radius:width-radius+1, radius:height-radius+1, :].copy()
for i in range(width-2*radius):
    for j in range(height-2*radius):
        result[i,j,2] = np.sum(np.multiply(image[i:i+size,j:j+size,2], kernel))

In [58]:
result[:,:,2]

array([[109, 109, 109, ..., 131, 131, 104],
       [109, 109, 109, ..., 128, 124, 101],
       [109, 109, 109, ..., 119, 132,  97],
       ...,
       [101, 109, 109, ..., 145, 145, 121],
       [113, 106, 109, ..., 145, 143, 119],
       [ 96,  91,  91, ..., 120, 120, 117]], dtype=uint8)

In [59]:
cv2.imshow("sample1", image2_hsi[:,:,2])
cv2.imshow("sample2", result[:,:,2])
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1